/**
 * Placeholder copy for the two legal documents.
 *
 * These strings are scaffolding — real text needs to be drafted by counsel
 * before public launch. Until then the pages render the placeholders so the
 * routes exist, the footer/signup links don't 404, and the acceptance
 * audit trail in the database is meaningful.
 *
 * Versions here must match what apps/api/config/legal.js declares as
 * current. When you ship new copy, bump both — that's what triggers the
 * "you accepted v2026-05-18, current is v2026-08-01, please re-accept"
 * prompt later on.
 */

import { branding } from '../../branding';

export const TERMS_VERSION   = '2026-05-18';
export const PRIVACY_VERSION = '2026-05-18';

// Shorthand used in the copy below — all brand strings come from
// src/branding.ts so a white-label deployment only edits that one file.
const brand = branding.productName;

export interface LegalDoc {
  title:    string;
  version:  string;
  intro:    string;
  sections: Array<{ heading: string; body: string }>;
}

export const TERMS_OF_SERVICE: LegalDoc = {
  title:   'Terms of Service',
  version: TERMS_VERSION,
  intro: `These Terms govern your use of the ${brand} platform. This is placeholder copy — final terms will be drafted by counsel before public launch. By using ${brand} you agree to the version of this document in effect on the date you signed up; we will notify you if a new version requires re-acceptance.`,
  sections: [
    {
      heading: '1. The Service',
      body: `${brand} is a software-as-a-service platform for managing IoT door locks. The platform issues commands to and receives events from physical devices over a third-party cellular network. ${brand} is not a replacement for life-safety systems or emergency egress hardware.`,
    },
    {
      heading: '2. Accounts and Eligibility',
      body: `Accounts are available to businesses. The first user to register a company becomes that company's Admin. You are responsible for keeping account credentials confidential and for all activity under your account.`,
    },
    {
      heading: '3. Hardware',
      body: `Hardware is purchased separately and is governed by the terms of the sale between you and your supplier or reseller. This platform manages devices; it does not sell them.`,
    },
    {
      heading: '4. Acceptable Use',
      body: `You agree not to use the platform for unlawful purposes, to gain unauthorized access to any building or asset, or to interfere with another customer's use of the service.`,
    },
    {
      heading: '5. Service Availability',
      body: `${brand} targets high availability but does not guarantee uninterrupted service. The platform depends on a third-party cellular network (Simkura). Outages of the upstream network may temporarily prevent commands from reaching devices.`,
    },
    {
      heading: '6. Limitation of Liability',
      body: `To the maximum extent permitted by law, ${brand} is not liable for indirect, incidental, or consequential damages arising from the use of the platform or any physical event involving a managed device. Final liability limits will be set in the counsel-reviewed version of this document.`,
    },
    {
      heading: '7. Termination',
      body: `Either party may terminate this agreement on notice. On termination, the platform will retain access logs for the period required by applicable law and will provide a reasonable export of your data on request.`,
    },
    {
      heading: '8. Changes to These Terms',
      body: `When these Terms change in a way that materially affects your rights, we will notify you and, where appropriate, ask you to re-accept the updated version.`,
    },
    {
      heading: '9. Contact',
      body: `Questions about these Terms can be sent to ${branding.legalEmail}.`,
    },
  ],
};

export const PRIVACY_POLICY: LegalDoc = {
  title:   'Privacy Policy',
  version: PRIVACY_VERSION,
  intro: `This Privacy Policy describes how ${brand} collects, uses, and shares information. This is placeholder copy — the final policy will be reviewed by counsel and will reflect the specific privacy regimes (e.g. GDPR, CCPA) that apply to ${brand}'s customer base.`,
  sections: [
    {
      heading: '1. Information We Collect',
      body: `Account information (name, email, phone, company) and operational data generated by your use of the platform — including door-access events, credential assignments, and device status.`,
    },
    {
      heading: '2. Door-Access Events',
      body: `When a credential opens a door, ${brand} records the event (device, credential, timestamp). These records are visible to the workspace that owns the device. We treat them as sensitive operational data and do not sell or share them with third parties for advertising purposes.`,
    },
    {
      heading: '3. How We Use Information',
      body: `To operate and improve the service, communicate with you about your account, process payments, and meet legal obligations. Aggregated, de-identified usage statistics may be used for internal analytics.`,
    },
    {
      heading: '4. Sharing',
      body: `We share information with subprocessors that help us operate the service (e.g. cellular connectivity provider, payment processor, email delivery), under contractual terms that restrict their use of the data. A current list of subprocessors is available on request.`,
    },
    {
      heading: '5. Retention',
      body: `Account data is retained for as long as your account is active and for a reasonable period afterward. Door-access events are retained according to the retention setting on each workspace.`,
    },
    {
      heading: '6. Your Rights',
      body: `Depending on where you live you may have the right to access, correct, or delete personal information we hold about you, and to object to certain processing. Email ${branding.privacyEmail} to exercise these rights.`,
    },
    {
      heading: '7. Security',
      body: `We use industry-standard measures to protect the information we hold. No system is fully secure, and we cannot guarantee absolute security of data transmitted over the internet.`,
    },
    {
      heading: '8. Changes to This Policy',
      body: `We will notify you of material changes to this policy and, where appropriate, ask you to acknowledge the update.`,
    },
    {
      heading: '9. Contact',
      body: `Questions about this Policy can be sent to ${branding.privacyEmail}.`,
    },
  ],
};
